[[redirects]]
  from = "https://earvinpiamonte.netlify.app/*"
  to = "https://earvinpiamonte.com/:splat"
  force = true

[[redirects]]
  from = "/np"
  to = "https://www.youtube.com/watch?v=b9THtRNlVCk"
  force = true
