[[redirects]]
  from = "https://earvinpiamonte.netlify.app/*"
  to = "https://earvinpiamonte.com/:splat"
  force = true

[[redirects]]
  from = "/np"
  to = "https://open.spotify.com/track/2DqhE7xzpGNsKYbptqblJg?si=AAq7uig7TVaaQwnX7R2nTw"
  force = true

[[redirects]]
  from = "/jennie"
  to = "https://www.youtube.com/watch?v=b9THtRNlVCk"
  force = true

[[redirects]]
  from = "/yow"
  to = "https://www.youtube.com/watch?v=g8eGiiwUD9w"
  force = true
