[[redirects]]
  from = "https://earvinpiamonte.netlify.app/*"
  to = "https://earvinpiamonte.com/:splat"
  force = true

[[redirects]]
  from = "/np"
  to = "https://www.youtube.com/watch?v=uODuvT8m2-o"
  force = true

[[redirects]]
  from = "/jennie"
  to = "https://www.youtube.com/watch?v=b9THtRNlVCk"
  force = true

[[redirects]]
  from = "/yow"
  to = "https://www.youtube.com/watch?v=g8eGiiwUD9w"
  force = true
