[[redirects]]
  from = "https://earvinpiamonte.netlify.app/*"
  to = "https://earvinpiamonte.com/:splat"
  force = true

[[redirects]]
  from = "/nxt-2-u"
  to = "https://www.youtube.com/watch?v=9IVO5Dsz1KI"
  force = true
